spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/estoquito
    username: root
    password: QWE123QWEbighorse0420
    platform: mysql
    initialization-mode: always
